#!/bin/bash
# this file will be overwritten by the project setup script
SIMICS_BASE_PACKAGE="/home/racter/SIMICS Packages/simics-6.0.128"
export SIMICS_BASE_PACKAGE
if [ -f "/home/racter/Desktop/PI-Ensambla/proyecto-equipo/simics-project/.package-list" ]; then
    exec "/home/racter/SIMICS Packages/simics-6.0.128/bin/simics-eclipse" --package-list "/home/racter/Desktop/PI-Ensambla/proyecto-equipo/simics-project/.package-list" --project "/home/racter/Desktop/PI-Ensambla/proyecto-equipo/simics-project" "$@"
else
    exec "/home/racter/SIMICS Packages/simics-6.0.128/bin/simics-eclipse" --project "/home/racter/Desktop/PI-Ensambla/proyecto-equipo/simics-project" "$@"
fi
